# llama-laya-cli -m <checkpoint dir>: converted once into the GGUF cache, then a cache hit; the cached
# GGUF is byte-identical to the Python converter (tests/laya/convert/golden.sha256) and gives the same
# output as -m <that GGUF>; a broken checkpoint fails cleanly (tools/decision/decision-checkpoint.h).
#
# usage: cmake -DCLI=<llama-laya-cli> -DFIXTURES=<tests/laya/convert> -DINPUTS="<a.json>|<b.json>" -DWORK=<scratch dir>
#              -P checkpoint-cli.cmake

foreach (var CLI FIXTURES INPUTS WORK)
    if (NOT DEFINED ${var})
        message(FATAL_ERROR "checkpoint-cli.cmake: -D${var}=... is required")
    endif()
endforeach()

string(REPLACE "|" ";" INPUTS "${INPUTS}")
set(n_checks 0)

# run the CLI; sets <prefix>_rc, <prefix>_out, <prefix>_err
function(run_cli prefix)
    execute_process(COMMAND ${CLI} ${ARGN} RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
    set(${prefix}_rc  "${rc}"  PARENT_SCOPE)
    set(${prefix}_out "${out}" PARENT_SCOPE)
    set(${prefix}_err "${err}" PARENT_SCOPE)
endfunction()

function(golden_sha fixture outtype result)
    file(STRINGS "${FIXTURES}/golden.sha256" lines REGEX "^${fixture}-${outtype}\\.gguf ")
    list(LENGTH lines n)
    if (NOT n EQUAL 1)
        message(FATAL_ERROR "no golden sha256 for ${fixture} ${outtype}")
    endif()
    string(REGEX REPLACE ".* ([0-9a-f]+)$" "\\1" sha "${lines}")
    set(${result} "${sha}" PARENT_SCOPE)
endfunction()

# the output without its "model" line (-m as given)
function(strip_model text result)
    string(REGEX REPLACE "\n  \"model\": [^\n]*" "" t "${text}")
    set(${result} "${t}" PARENT_SCOPE)
endfunction()

file(REMOVE_RECURSE "${WORK}")
file(MAKE_DIRECTORY "${WORK}")

foreach (fixture laya-tiny-ms-v0.1-8M laya-bl-tiny-instruct-30K)
    set(cache "${WORK}/cache-${fixture}")
    golden_sha(${fixture} f16 want)
    set(first TRUE)
    foreach (input ${INPUTS})
        # the first run converts, every later one hits the cache
        run_cli(a -m "${FIXTURES}/${fixture}" --decision-convert-cache "${cache}" -f "${input}")
        if (NOT a_rc EQUAL 0)
            message(FATAL_ERROR "FAIL: ${fixture}: -m DIR exited ${a_rc}:\n${a_err}")
        endif()
        if (first AND NOT a_err MATCHES "laya: converted: ")
            message(FATAL_ERROR "FAIL: ${fixture}: the first -m DIR run did not convert:\n${a_err}")
        endif()
        set(first FALSE)
        run_cli(b -m "${FIXTURES}/${fixture}" --decision-convert-cache "${cache}" -f "${input}")
        if (NOT b_rc EQUAL 0 OR NOT b_err MATCHES "laya: cache hit: " OR b_err MATCHES "laya: converted")
            message(FATAL_ERROR "FAIL: ${fixture}: second -m DIR run is not a cache hit:\n${b_err}")
        endif()
        if (NOT a_out STREQUAL b_out)
            message(FATAL_ERROR "FAIL: ${fixture}: converted and cache-hit runs differ")
        endif()

        file(GLOB_RECURSE ggufs "${cache}/*")
        list(LENGTH ggufs n)
        if (NOT n EQUAL 1)
            message(FATAL_ERROR "FAIL: ${fixture}: expected one file in the cache, got: ${ggufs}")
        endif()
        get_filename_component(name "${ggufs}" NAME)
        if (NOT name STREQUAL "${fixture}.gguf")
            message(FATAL_ERROR "FAIL: ${fixture}: cached file is named ${name}")
        endif()
        file(SHA256 "${ggufs}" got)
        if (NOT got STREQUAL want)
            message(FATAL_ERROR "FAIL: ${fixture}: cached GGUF sha256 ${got}, Python converter ${want}")
        endif()

        run_cli(g -m "${ggufs}" -f "${input}")
        strip_model("${a_out}" a_s)
        strip_model("${g_out}" g_s)
        if (NOT g_rc EQUAL 0 OR NOT a_s STREQUAL g_s OR a_s STREQUAL a_out)
            message(FATAL_ERROR "FAIL: ${fixture}: -m DIR and -m GGUF outputs differ for ${input}")
        endif()
        math(EXPR n_checks "${n_checks} + 1")
    endforeach()
endforeach()

# f32: another cache key, Python bytes
foreach (outtype f32)
    set(cache "${WORK}/cache-${outtype}")
    list(GET INPUTS 0 input)
    run_cli(q -m "${FIXTURES}/laya-tiny-ms-v0.1-8M" --decision-convert-cache "${cache}" --decision-convert-type ${outtype} -f "${input}")
    if (NOT q_rc EQUAL 0 OR NOT q_err MATCHES "laya: converted: ")
        message(FATAL_ERROR "FAIL: --decision-convert-type ${outtype}:\n${q_err}")
    endif()
    file(GLOB_RECURSE ggufs "${cache}/*.gguf")
    golden_sha(laya-tiny-ms-v0.1-8M ${outtype} want)
    file(SHA256 "${ggufs}" got)
    if (NOT got STREQUAL want)
        message(FATAL_ERROR "FAIL: ${outtype}: cached GGUF sha256 ${got}, Python converter ${want}")
    endif()
    math(EXPR n_checks "${n_checks} + 1")
endforeach()

# a broken checkpoint: clean error, nothing left in the cache
set(bad "${WORK}/bad/laya-tiny-ms-v0.1-8M")
file(COPY "${FIXTURES}/laya-tiny-ms-v0.1-8M" DESTINATION "${WORK}/bad")
file(WRITE "${bad}/encoder/config.json" "{\"hidden_size\": ")
list(GET INPUTS 0 input)
run_cli(x -m "${bad}" --decision-convert-cache "${WORK}/cache-bad" -f "${input}")
if (x_rc EQUAL 0 OR NOT x_err MATCHES "cannot convert checkpoint directory")
    message(FATAL_ERROR "FAIL: broken checkpoint: exit ${x_rc}:\n${x_err}")
endif()
file(GLOB_RECURSE left "${WORK}/cache-bad/*")
if (left)
    message(FATAL_ERROR "FAIL: broken checkpoint left files behind: ${left}")
endif()
math(EXPR n_checks "${n_checks} + 1")

# not a checkpoint (no rl_agent_config.json)
file(REMOVE "${bad}/rl_agent_config.json")
run_cli(y -m "${bad}" --decision-convert-cache "${WORK}/cache-bad" -f "${input}")
if (y_rc EQUAL 0 OR NOT y_err MATCHES "is a directory but not a laya checkpoint")
    message(FATAL_ERROR "FAIL: not a checkpoint: exit ${y_rc}:\n${y_err}")
endif()
math(EXPR n_checks "${n_checks} + 1")

# unknown outtype, and q8_0: convert_hf_to_gguf.py's q8_0 is not the precision-protected recipe, -m DIR does not offer it
foreach (outtype bf16 q8_0)
    run_cli(z -m "${FIXTURES}/laya-tiny-ms-v0.1-8M" --decision-convert-cache "${WORK}/cache-z" --decision-convert-type ${outtype} -f "${input}")
    if (z_rc EQUAL 0 OR NOT z_err MATCHES "must be f16 or f32")
        message(FATAL_ERROR "FAIL: --decision-convert-type ${outtype} was accepted:\n${z_err}")
    endif()
    math(EXPR n_checks "${n_checks} + 1")
endforeach()

# a flag without its value is an error, not a silent default
run_cli(v -m "${FIXTURES}/laya-tiny-ms-v0.1-8M" -f "${input}" --decision-convert-cache)
if (v_rc EQUAL 0 OR NOT v_err MATCHES "needs a value")
    message(FATAL_ERROR "FAIL: --decision-convert-cache without a value:\n${v_err}")
endif()
math(EXPR n_checks "${n_checks} + 1")

# a cache directory inside the checkpoint is refused before anything is created there
file(COPY "${FIXTURES}/laya-tiny-ms-v0.1-8M" DESTINATION "${WORK}/inside")
run_cli(w -m "${WORK}/inside/laya-tiny-ms-v0.1-8M" --decision-convert-cache "${WORK}/inside/laya-tiny-ms-v0.1-8M/cache/a" -f "${input}")
if (w_rc EQUAL 0 OR NOT w_err MATCHES "is inside the checkpoint directory" OR EXISTS "${WORK}/inside/laya-tiny-ms-v0.1-8M/cache")
    message(FATAL_ERROR "FAIL: cache inside the checkpoint:\n${w_err}")
endif()
math(EXPR n_checks "${n_checks} + 1")

file(REMOVE_RECURSE "${WORK}")
message(STATUS "checkpoint-cli: ${n_checks} checks passed")
